org_names = {
    'US': [
        'University of Southern California',
        'University of California', 'Johns Hopkins University',
        'IBM Research', 'Texas A& M University', 'Carnegie Mellon University',
        'Princeton University', 'University of Colorado Colorado Springs',
        'University of Chicago', 'Google Research', 'Google Brain',
        'Stevens Institute of Technology', 'Stanford University', 'MIT',
        'United Technologies Research Center', 'Intel Labs',
        'University of Illinois', 'Massachussetts Institute of Technology',
        'Microsoft Research', 'Caltech', 'WUSTL', 'Purdue University',
        'University of Texas', 'University of Massachusetts',
        'Cornell University and Cornell Tech', 'Google AI',
        'University of Washington', 'Columbia University', 'Google Inc.',
        'Brandeis University', 'University of Georgia', 'TTI at Chicago',
        'University of Minnesota', 'Cornell University',
        'Georgia Institute of Technology', 'Texas A&M University',
        'Yale University', 'Georgia State University',
        'University of Pennsylvania', 'University of Central Florida',
        'Massachusetts Institute of Technology',
        'University of Pittsburgh', 'Uber AI Labs', 'University of Colorado',
        'Brown University', 'UCLA', 'Georgia Tech', 'Harvard University',
        'Pittsburgh', 'Schlumberger Software Technology Innovation Center',
        'Weill Cornell Medicine', 'University of Maryland',
        'State University of New York at Buffalo', 'UIUC',
        'Indiana University Bloomington', 'Oregon State University',
        'Fred Hutchinson Cancer Research Center', 'Salk Institute',
        'Playground Global', 'The Ohio State University', 'UC Berkeley',
        'Stanford Graduate School of Business', 'Intel AI Lab',
        'George Washington University', 'University of Michigan',
        'University of Iowa', 'Tableau Software',
        'Harvey Mudd College', 'Iowa State University',
        'University of Miami', 'Penn State University',
        'Washington University', 'Stony Brook University',
        'USC Information Sciences Institute',
        'Binghamton University', 'University of North Carolina',
        'Rensselaer Polytechnic Institute', 'The Voleon Group', 'Microsoft',
        'Amazon Research', 'UT Austin', 'IBM', 'Adobe Research',
        'Duke University', 'Northeastern University', 'Facebook AI Research',
        'Stanford', 'UC Los Angeles', 'Rutgers University',
        'New York University', 'University of Rochester',
        'University of Utah', 'West Virginia University',
        'Toyota Technological Institute at Chicago', 'uw', 'Boston University',
        'California Institute of Technology', 'University at Buffalo',
        'Dartmouth College', 'Lehigh University', 'Google', 'M.I.T.',
        'University of Wisconsin-Madison', 'University of Florida', 'Facebook',
        'google', 'University of Virginia'],
    'GB': ['University College London', 'University of Oxford',
           'Imperial College London', 'DeepMind', 'University of Warwick',
           'University of Cambridge', 'PROWLER.io',
           'University of Edinburgh', 'University of Western Ontario',
           'University of Glasgow', 'Queen Mary University of London',
           'AimBrain Ltd.', 'University of Bath', 'University of Manchester'],
    'CN': ['Tianjin University', 'National University of Defense Technology',
           'Xidian University', 'Shanghai Jiao Tong University',
           'Tencent AI Lab', 'Peking University', 'Tsinghua University',
           'Fudan University', 'Dalian University of Technology',
           'University of Science and Technology of China',
           'Chinese Academy of Sciences', '4Paradigm Inc.',
           'SenseTime', 'Beijing University of Posts and Telecommunications',
           'Sun Yat-sen University', 'Nankai University',
           'Nanjing University', 'Sun Yat-Sen University',
           'Shenzhen Key Laboratory of Computational Intelligence',
           'Renmin University of China', 'Baidu Research', 'Huawei',
           'New York University Shanghai', 'Zhejiang University',
           'Hulu LLC', 'Hangzhou Dianzi University'],
    'TW': ['HTC Research', 'National Tsing Hua University'],
    'HK': ['The Chinese University of Hong Kong', 'The University of Hong Kong'],
    'AT': ['University of Innsbruck', 'University of Vienna'],
    'KR': [
        'Korea Advanced Institute of Science and Technology', 'KAIST',
        'Seoul National University', 'Yonsei University', 'Lunit Inc.',
        'Ulsan National Institute of Science and Technology', 'UNIST'],
    'ZA': ['Stellenbosch University',
           'University of the Witwatersrand'],
    'CH': ['École Polytechnique Fédérale de Lausanne', 'ETH Zürich',
           'EPFL', 'ETH Zurich', 'University of Geneva',
           'The Swiss AI Lab IDSIA'],
    'JP': ['The University of Tokyo', 'RIKEN Center for Brain Science',
           'Keio Univ.', 'Keio University',
           'National Institute of Advanced Industrial Science and Technology',
           'The University of Electro-Communications',
           'Toyota Central R&D Labs.',
           'Sony Imaging Products & Solutions Inc.',
           'Okinawa Institute of Science and Technology Graduate University'],
    'NL': ['University of Amsterdam', 'Radboud University',
           'Navinfo Europe Research'],
    'CA': ['McGill University', 'University of Toronto',
           'University of Waterloo', 'University of British Columbia',
           'University of Alberta', 'University of Calgary',
           'Element AI', 'D-Wave Systems Inc.',
           'U. of Ontario Inst. of Tech.', 'Simon Fraser University',
           'Vector Institute', 'ÉTS Montreal'],
    'FR': ['Université Paris-Saclay', 'University of Rennes', 'EURECOM',
           'PSL Research University', 'Ecole Polytechnique',
           'Sorbonne Université', 'École Normale Supérieure',
           'fifty-five', 'Inria', 'Université Claude Bernard Lyon 1',
           'Université de Bordeaux', 'Université Paris-Saclay'],
    'IT': ['Università degli Studi di Pavia', 'Politecnico di Torino',
           'Politecnico di Milano', 'Sapienza University',
           'Istituto Italiano di Tecnologia'],
    'DE': ['TU Dortmund University',
           'Bosch Center for Artificial Intelligence',
           'Max-Planck Institute for Intelligent Systems',
           'Max-Planck-Institute for Intelligent Systems',
           'Max Planck Institute for Intelligent Systems',
           'Max Planck Institute for Informatics',
           'University of Tübingen', 'MPI-SWS',
           'Technische Universität München',
           'TU Darmstadt', 'École polytechnique fédérale de Lausanne',
           'Ostwestfalen-Lippe University of Applied Sciences',
           'Friedrich-Schiller-Universität Jena',
           'Freie Universität Berlin',
           'École Polytechnique Fédérale de Lausanne',
           'TU Dortmund', 'Technical University of Munich',
           'Amazon Berlin', 'Technische Universität Darmstadt'],
    'AU': ['The University of Sydney', 'University of Technology Sydney',
           'Macquarie University', 'University of Melbourne',
           'Deakin University', 'UNSW Sydney',
           'Australian National University'],
    'PK': ['Information Technology University Lahore'],
    'TH': ['Vidyasirimedhi Institute of Science and Technology'],
    'RU': ['Skolkovo Institute of Science and Technology',
           'Moscow Institute of Physics and Technology',
           'Lomonosov Moscow State University'],
    'ES': ['Universitat Autònoma de Barcelona',
           'Universidad Carlos III de Madrid'],
    'DK': ['IT University of Copenhagen', 'University of Copenhagen',
           'Aarhus University'],
    'IL': ['Weizmann Institute of Science', 'Tel Aviv University',
           'Bar Ilan University', 'Bar-Ilan University',
           'Technion', 'Israel Institute of Technology',
           'The Hebrew University of Jerusalem',
           'Ariel University'],
    'SG': ['National University of Singapore',
           'Singapore University of Technology and Design',
           'Nanyang Technological University',
           'Singapore Management University'],
    'BR': ['Universidade Federal de Minas Gerais', 'UFMG'],
    'PL': ['Jagiellonian University',
           'Wroclaw University of Science and Technology',
           'Poznan University of Technology'],
    'BE': ['KU Leuven'],
    'IN': ['Indian Institute of Science', 'Indian Institute of Technology'],
    'FI': ['Aalto University'],
    'SE': ['Lund University', 'Uppsala University', 'KTH'],
    'CL': ['Universidad de Chile']
}


def test_abbreviation(src, title):
    abbreviation_dict = {
        'VAEs': 'Variational Autoencoders',
        'CNNs?': 'Networks?'
    }
    src_last = src.split(' ')[-1]
    if src_last in abbreviation_dict and title.endswith(
            abbreviation_dict[src_last]):
        return True
    return False


if __name__ == "__main__":
    pass
